# Generated by Django 4.2.5 on 2023-10-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0004_alter_airplane_airplane_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(
                blank=True, related_name="flights", to="airport.crew"
            ),
        ),
    ]
